### PR TITLE
Added a better help command. 

### PR DESCRIPTION
**Pull request by thatrandomperson5**
If you wan’t something else, tell me. I can make pretty good help commands. The old one is was the default and this one is a little bit better.

### CODE REVIEW

**Comment by BenitzCoding** [comment]
@JDJGInc

**Comment by thatrandomperson5** [comment]
> @JDJGInc

They said they’d let frostii handle it

**Comment by arqvt** [comment]
# Pros
This is a discord.py built-in subclassable help command which is good for our case. It doesn't require any external libs.

Which means i approve and will merge.

**Comment by arqvt** [comment]
May you re-run with black formatting? We won't merge it unless you do that.

**Comment by thatrandomperson5** [comment]
> 

Sorry, I do not know how to. Do I need GitHub actions?

**Comment by thatrandomperson5** [comment]
> May you re-run with black formatting? We won't merge it unless you do that.

✅ @FrostiiWeeb

**Comment by BenitzCoding** [comment]
> > @JDJGInc
> 
> They said they’d let frostii handle it

 I didn't see message, where?

**Comment by arqvt** [comment]
Alright. Seems good, will merge now.

**Comment by thatrandomperson5** [comment]
> > > @JDJGInc
> > 
> > 
> > They said they’d let frostii handle it
> 
> I didn't see message, where?

Dm’s

**Pull request merged**
